name: MLOPS Assignment Workflow

on:
  push:
    branches:
      - main
      - development
      - feature/workflow
      - feature/workflow-2
  workflow_dispatch:

jobs:
  mlops-pipeline:
    name: MLOPS Pipeline
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Python
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv
          python3 --version
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      
      - name: Clean data
        run: |
          cd ModelCleaning
          python3 Cleandata.py

      - name: Train Data
        run: |
            cd ModelCleaning
            python3 train_test_dataset.py