name: MLOPS Assignment Workflow

on:
  push:
    branches:
      - main
      - development
      - feature/workflow
      - feature/workflow-2
  workflow_dispatch:

jobs:
  mlops-pipeline:
    name: MLOPS Pipeline
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Python
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv
          python3 --version
      
      - name: Create virtual environment and install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Clean data
        run: |
          source venv/bin/activate
          cd ModelCleaning
          python Cleandata.py

      - name: Train Data
        run: |
          source venv/bin/activate
          cd ModelCleaning
          python train_test_dataset.py

      - name: Install Docker & Verify Installation
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          
          sudo usermod -aG docker $USER
          
          sudo systemctl start docker
          sudo systemctl enable docker
          
          newgrp docker
          
          docker --version

      - name: Build & Tag Docker Image
        run: |
          sudo docker build -t ice-cream-api:latest .
          
          # Tag for Google Container Registry
          sudo docker tag ice-cream-api:latest us-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/ice-cream-api:latest
          sudo docker tag ice-cream-api:latest us-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/ice-cream-api:${{ github.sha }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APP_CREDS }}

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      - name: Push Docker Image to GCR
        run: |
          sudo docker push us-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/ice-cream-api:latest
          sudo docker push us-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/ice-cream-api:${{ github.sha }}

      - name: Deploy to Docker Swarm on GCP
        run: |
          # Connect to your GCP Docker Swarm manager node
          gcloud compute ssh ${{ secrets.SWARM_MANAGER_INSTANCE }} \
            --zone=${{ secrets.GOOGLE_ZONE }} \
            --command="
              # Pull the latest image
              docker pull us-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/ice-cream-api:latest
              
              # Deploy/update the service in swarm
              docker service create \
                --name ice-cream-api \
                --replicas 3 \
                --publish 80:5000 \
                --update-config \
                us-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/ice-cream-api:latest || \
              docker service update \
                --image us-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/ice-cream-api:latest \
                ice-cream-api
            "