name: MLOPS Assignment Workflow

on:
  push

jobs:
  job1:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

  job2:
    name: check python version
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Check Python version
        run: |
          python --version
          python -c "import sys; print(f'Python {sys.version}')"