name: MLOPS Assignment Workflow

on:
  push

jobs:
  job1:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  job2:
    name: check python version
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Check Python version
        run: |
          python --version
          python -c "import sys; print(f'Python {sys.version}')"