name: MLOPS Assignment Workflow

on:
  push:
    branches:
      - main
      - development
      - feature/workflow
      - feature/workflow-2
  workflow_dispatch:

jobs:
  job1:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

  job2:
    name: check python version
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Check Python version
        run: |
          python --version
          python -c "import sys; print(f'Python {sys.version}')"

  job3:
    name: checkout code
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: clean data
        run: |
          python ModelCleaning/Cleandata.py