name: MLOPS Assignment Workflow

on:
  push:
    branches:
      - main
      - development
      - feature/workflow
      - feature/workflow-2
  workflow_dispatch:

jobs:
  mlops-pipeline:
    name: MLOPS Pipeline
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Python
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv
          python3 --version
      
      - name: Create virtual environment and install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Clean data
        run: |
          source venv/bin/activate
          cd ModelCleaning
          python Cleandata.py

      - name: Train Data
        run: |
          source venv/bin/activate
          cd ModelCleaning
          python train_test_dataset.py

      - name: Deploy Flask API
        run: |
          source venv/bin/activate
          python app.py &
          sleep 5
          python test_api.py